---
output:
  html_document:
    df_print: paged
  pdf_document:
    toc: yes
fontsize: 14pt
mainfont: Arial
header-includes: \usepackage{amsmath}
---

## Protocol

#### ASAE S580.1 JAN03 "Testing and Reporting Solar Cooker Performance protocol".

This Standard specifies that test results be presented as cooking power, in Watts, normalized for ambient conditions, relative to the temperature difference between cooker contents and ambient air, both as a plot and as a regression equation for no fewer than 30 total observations over three different days.

**Uncontrolled (Weather) Variables**

_Average Wind._ Tests shall be conducted when average wind during the duration of the test is less than 1.0 m/s, measured at the elevation of the cooker being tested and within ten meters of it.

_Maximum Wind._ Should the wind exceed 2.5 m/s for more than ten minutes the test data shall be discarded. Wind Shielding. If a wind shelter is required, 1) it shall be designed so as to not interfere with incoming total radiation and 2) the wind instrumentation shall be co-located with the cooker in the same wind shadow.

_Ambient temperature._ Tests should be conducted when ambient temperatures are between 20 and 35 °C. Water temperature. Test data shall be recorded while cooking vessel contents (water) are at temperatures between 5 °C above ambient and 5 °C below local boiling temperature.

_Insolation._ Available solar energy shall be measured in the plane perpendicular to direct beam radiation (the maximum reading) using a radiation pyranometer. Variation in measured insolation greater than 100 W/m2 during a ten-minute interval, or readings below 450 W/m2 or above 1100 W/m2 during the test shall render the test invalid. For convenience, the pyranometer may be fixed on the cooker at the average beam radiation zenith angle as calculated for the entire test period.

_Solar zenith and azimuth angle._ Tests should be conducted between 10:00 and 14:00 solar time. Exceptions necessitated by solar variability or ambient temperature shall be specially noted.

**Controlled (Cooker) Variables**

_Loading._ Cookers shall have 7,000 grams potable water per square meter intercept area distributed evenly between the cooking vessels supplied with the cooker. If no cooking vessels are provided, inexpensive aluminum cooking vessels painted black shall be used.

_Water mass._ The mass of water should be determined with an electronic balance to the nearest gram using a pre-wetted container.

_Tracking._ Azimuth angle tracking frequency should be appropriate to the cooker’s acceptance angle. Box-type cookers typically require adjustment every 15 to 30 minutes or when shadows appear on the absorber plate. Concentrating-type units may require more frequent adjustment to keep the solar image focused on the cooking vessel or absorber. With box-type cookers, zenith angle tracking may be unnecessary during a two hour test conducted at mid-day. Testing should be representative of local conditions, i.e.; how the typical consumer is expected to use the cooker.

_Temperature sensing._ Water and air temperature should be sensed with thermocouples. Each thermocouple junction shall be immersed in the water in the cooking vessel(s) and secured 10 mm above the bottom, at center. Thermocouple leads should pass through the cooking vessel lid inside a thermally nonconductive sleeve to protect the thermocouple wire from bending and temperature extremes. The sleeve should be secured with 100% silicone caulk to reduce water vapor loss.

**Recording**

The average water temperature (°C) of all cooking vessels in one cooker shall be recorded at intervals not to exceed ten minutes, and should be in units of Celsius to the nearest one tenth of a degree. Solar insolation (W/m2), ambient temperature (°C), and wind speed (m/s) shall also be recorded at intervals not to exceed ten minutes. Record and report the frequency of attended (manual) tracking, if any. Report azimuth angle(s) during the test. Report the test site elevation and latitude, and the dates of testing.

**Cooking Power**

The change in water temperature for each non-overlapping ten-minute interval was multiplied by the mass and specific heat capacity of the water contained in the cooking vessel(s). This product shall be divided by the 600 seconds contained in a ten-minute interval, as:

$$P_i = \frac{(T_2 - T_1)\cdot M\cdot C_{v}}{600}$$ where:

- $P_{i}$ cooking power (W) for interval i
- $T_2$ final water temperature (°C)
- $T_1$ initial water temperature (°C)
- $M$ water mass (kg)
- $C_{v}$ heat capacity of water (4186 J/[kg·°C])

**Interval Averages**

The average insolation, average ambient temperature, and average cooking vessel contents temperature were calculated in each interval.

**Standardized Cooking Power**

The cooking power for each interval was corrected to a standard insolation of 700 $W/m^2$ by multiplying the interval observed cooking power by 700 $W/m^2$ and dividing by the interval average insolation recorded during the corresponding interval.

$$P_{s} = P_{i}\cdot\frac{700}{I_{i}}$$ where:

- $P_{s}$ standardized cooking power (W)
- $P_{i}$ interval cooking power (W), as calculated above
- $I_{i}$ interval average solar insolation (W/m2)

**Temperature Difference**

Ambient temperature for each interval is to be subtracted from the average cooking vessel contents temperature for each corresponding interval:

$$T_{d} = T_{w} - T_{a}$$

where:

- $T_{d}$ temperature difference (°C)
- $T_{w}$ water temperature (°C)
- $T_{a}$ ambient air temperature (°C)

**Linear regression**

A linear regression of the plotted points shall be used to find the relationship between cooking power and temperature difference in terms of intercept, a (W), and slope, b (W/ °C):

$$P_{s} = a + b \cdot T_{d}$$.

No fewer than 30 total observations from three different days shall be employed. The coefficient of determination ($r^2$) or proportion of variation in cooking power that can be attributed to the relationship found by regression should be higher than 0.75 or specially noted.

**Single measure of performance**

The value for standardized cooking power, Ps (W), shall be computed for a temperature difference, Td, of 50 °C using the regression relationship.

**Reporting**

A plot of the relationship between standardized cooking power and temperature difference shall be presented with the equation. The report shall also state the standardized cooking power at a temperature difference of 50 °C.

### References

Funk, P.A. 2000. Evaluating the international standard procedure for testing solar cookers and reporting performance.Solar Energy 68(1):1--7.

Mullick S.C., Kandpal T.C., and Saxena A.K. 1987. Thermal test procedure for box-type solar cookers. Solar Energy 39(4):353--360.
